import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.worker.mjs";

const PASS="APROVADO",FAIL="REPROVADO",WARN="ALERTA",REVIEW="REVISÃO MANUAL",NA="NÃO APLICÁVEL";
const CM=72/2.54,A4=[595.276,841.89],LEFT=3*CM,RIGHT=2*CM;
const $=s=>document.querySelector(s); let report=null;
const ck=(id,category,rule,source,status,evidence,correction="",mandatory=true,level="automático")=>({id,category,rule,source,status,evidence,correction,mandatory,level});
const norm=s=>String(s||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toUpperCase();
const compact=s=>norm(s).replace(/[^A-Z0-9]/g,"");
const isTextFallback=s=>{const x=compact(s);return x.includes("TEXGYRETERMESX")||(x.includes("TEXGYRETERMES")&&!x.includes("MATH"))||x.includes("TEXGYREHEROS")};
const verdict=cs=>cs.some(c=>c.mandatory&&c.status===FAIL)?FAIL:cs.some(c=>c.mandatory&&c.status===REVIEW)?"REVISÃO NECESSÁRIA":cs.some(c=>[WARN,REVIEW].includes(c.status))?"APROVADO NOS CHECKS AUTOMÁTICOS, COM RESSALVAS":"APROVADO NOS CHECKS AUTOMÁTICOS";

function save(name,data,type){const b=new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function csv(v){return `"${String(v??"").replaceAll('"','""')}"`}
function render(r){$("#summary").classList.remove("hidden");$("#report-section").classList.remove("hidden");$("#verdict").textContent=r.verdict;$("#file-name").textContent=r.file;$("#page-count").textContent=r.pages;const body=$("#report-body");body.replaceChildren();for(const c of r.checks){const tr=document.createElement("tr");for(const [i,v] of [c.status,c.category,c.rule,c.source,c.evidence,c.correction].entries()){const td=document.createElement("td");td.textContent=v;if(i===0)td.className=c.status===PASS?"status-pass":c.status===FAIL?"status-fail":c.status===WARN?"status-warn":"status-review";tr.append(td)}body.append(tr)}$("#counts").textContent=[PASS,FAIL,WARN,REVIEW,NA].map(s=>`${s}: ${r.checks.filter(c=>c.status===s).length}`).join(" · ");["#export-json","#export-csv","#print-report"].forEach(s=>$(s).disabled=false)}

async function analyze(file,profile){
 const data=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data}).promise,meta=await pdf.getMetadata(),outline=await pdf.getOutline(),js=await pdf.getJSActions().catch(()=>null);
 const pages=[],families=new Set();let tagged=false;
 for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),vp=p.getViewport({scale:1}),tc=await p.getTextContent(),st=await p.getStructTree().catch(()=>null);if(st)tagged=true;for(const it of tc.items){const f=tc.styles?.[it.fontName]?.fontFamily;if(f)families.add(f)}pages.push({n,w:vp.width,h:vp.height,items:tc.items,text:tc.items.map(i=>i.str).join(" ").replace(/\s+/g," ")})}
 const cs=[ck("pdf.open","Integridade","PDF legível","Pré-requisito técnico",PASS,`${pdf.numPages} páginas processadas localmente.`)];
 const bad=pages.filter(p=>Math.abs(p.w-A4[0])>1.8||Math.abs(p.h-A4[1])>1.8).map(p=>p.n);cs.push(ck("layout.a4","Layout","Papel A4","NBR 14724:2024 / UFC",bad.length?FAIL:PASS,bad.length?`Páginas fora de A4: ${bad.join(", ")}`:"Todas as páginas em A4.",bad.length?"Configure A4 em todas as páginas.":""));
 const out=[];for(const p of pages)for(const i of p.items){const s=i.str?.trim();if(!s)continue;const x=i.transform[4],x1=x+(i.width||0),y=i.transform[5];if(/^\d+$/.test(s)&&y>p.h-75)continue;if(x<LEFT-1.8||x1>p.w-RIGHT+3)out.push([p.n,s.slice(0,20),x.toFixed(1),x1.toFixed(1)])}cs.push(ck("layout.margins","Layout","Margens horizontais 3 cm / 2 cm","NBR 14724:2024 / UFC",out.length?FAIL:PASS,out.length?`Exemplos: ${JSON.stringify(out.slice(0,8))}`:"Nenhum texto ultrapassa as margens.",out.length?"Recuar o elemento para dentro da mancha gráfica.":"",true,"geométrico"));
 const fam=[...families],fn=fam.map(compact),lit=fam.filter((_,i)=>fn[i].includes("TIMESNEWROMAN")||fn[i].startsWith("ARIAL")),fb=fam.filter(isTextFallback);let fs=lit.length&&!fb.length?PASS:fb.length&&!lit.length?(profile==="portable"?WARN:FAIL):REVIEW;cs.push(ck("font.family","Tipografia","Arial ou Times New Roman literal","Guia UFC - Formato",fs,`Literais: ${lit.join(", ")||"nenhuma"}; fallback textual: ${fb.join(", ")||"nenhum"}.`,fs===PASS?"":"Use fonte-estrita=sim e confirme no modo Deep/CLI.",profile!=="portable","heurístico"));cs.push(ck("font.embedding","Tipografia","Todas as fontes incorporadas","PDF/A / preservação",REVIEW,"Web/Lite não certifica incorporação de todas as fontes.","Execute o modo Deep/CLI.",profile!=="portable","profundo"));
 const u=norm(pages.map(p=>p.text).join("\n")),req=[["cover","Capa","UNIVERSIDADE FEDERAL DO CEARA"],["approval","Folha de aprovação","BANCA EXAMINADORA"],["resumo","Resumo","RESUMO"],["abstract","Abstract","ABSTRACT"],["toc","Sumário","SUMARIO"],["refs","Referências","REFERENCIAS"]];for(const [id,label,t] of req){const ok=u.includes(t);cs.push(ck(`structure.${id}`,"Estrutura",label,"ABNT/UFC",ok?PASS:FAIL,ok?"Elemento localizado.":"Elemento não localizado.",ok?"":`Inclua ${label.toLowerCase()}.`))}
 for(const [id,t] of [["keywords","PALAVRAS-CHAVE"],["keywords-en","KEYWORDS"]]){const ok=u.includes(t);cs.push(ck(`structure.${id}`,"Resumo",t,"NBR 6028:2021 / UFC",ok?PASS:FAIL,ok?"Campo localizado.":"Campo ausente.",ok?"":`Inclua ${t.toLowerCase()}.`))}
 const inf=meta.info||{},title=inf.Title||meta.metadata?.get?.("dc:title")||"",author=inf.Author||meta.metadata?.get?.("dc:creator")||"",lang=inf.Language||meta.metadata?.get?.("dc:language")||"";cs.push(ck("meta.lang","Metadados","Idioma principal","WCAG / preservação",lang?PASS:WARN,lang||"Não exposto pelo PDF.js.",lang?"":"Defina pt-BR.",false));cs.push(ck("meta.title","Metadados","Título do PDF","Boa prática de repositório",title?PASS:WARN,title||"Ausente.",title?"":"Defina o título PDF/XMP.",false));cs.push(ck("meta.author","Metadados","Autor do PDF","Boa prática de repositório",author?PASS:WARN,author||"Ausente.",author?"":"Defina o autor PDF/XMP.",false));
 const acc=profile==="accessibility";cs.push(ck("access.tagged","Acessibilidade","PDF estruturado/tagged","PDF/UA / WCAG",tagged?PASS:(acc?FAIL:WARN),tagged?"Árvore de estrutura detectada.":"Árvore de estrutura não detectada.",tagged?"":"Gere PDF tagged.",acc));cs.push(ck("access.bookmarks","Acessibilidade","Bookmarks","WCAG PDF2",outline?.length?PASS:WARN,outline?.length?`${outline.length} entradas de nível superior.`:"Não detectados.",outline?.length?"":"Adicione bookmarks.",false));cs.push(ck("security.javascript","Integridade","Sem JavaScript embutido","Preservação",js&&Object.keys(js).length?WARN:PASS,js&&Object.keys(js).length?"Ações JavaScript detectadas.":"Nenhuma ação JavaScript detectada.","",false));
 cs.push(ck("pdfa.deep","PDF/A","Validação estrutural PDF/A","SiBi-UFC exige PDF/A",REVIEW,"Web/Lite não substitui validação ISO completa.","Execute o CLI/Deep com veraPDF -f 2b.",profile!=="portable","profundo"));cs.push(ck("catalog.optional","Depósito UFC","Ficha catalográfica visual","IN Conjunta UFC nº 2/2026",NA,"Representação visual facultativa.","",false));cs.push(ck("approval.signatures","Depósito UFC","Folha de aprovação sem assinaturas digitalizadas","Normas SiBi-UFC",REVIEW,"Exige inspeção visual.","Use a folha sem assinaturas no depósito.",false,"manual"));cs.push(ck("capes","Depósito UFC","Agradecimento CAPES quando aplicável","Portaria CAPES nº 206/2018",REVIEW,"Depende do financiamento.","Inclua a redação obrigatória se aplicável.",false,"condicional"));
 if(acc){cs.push(ck("access.alt","Acessibilidade","Texto alternativo adequado","PDF/UA / WCAG",REVIEW,"Qualidade exige revisão humana.","Revise /Alt e artefatos decorativos.",true,"manual"));cs.push(ck("access.order","Acessibilidade","Ordem de leitura lógica","PDF/UA / WCAG",REVIEW,"Exige teste com tecnologia assistiva.","Revise a ordem de leitura.",true,"manual"))}
 return {file:file.name,pages:pdf.numPages,profile,verdict:verdict(cs),checks:cs,mode:"web-lite-local",generatedAt:new Date().toISOString()};
}

$("#analyze").addEventListener("click",async()=>{const f=$("#pdf-file").files?.[0];if(!f)return alert("Selecione um PDF.");const b=$("#analyze");b.disabled=true;b.textContent="Validando...";try{report=await analyze(f,$("#profile").value);render(report)}catch(e){console.error(e);alert(`Falha na validação: ${e.message||e}`)}finally{b.disabled=false;b.textContent="Validar PDF"}});
$("#export-json").addEventListener("click",()=>report&&save("relatorio-validacao-ufc.json",JSON.stringify(report,null,2),"application/json;charset=utf-8"));
$("#export-csv").addEventListener("click",()=>{if(!report)return;const h=["Status","Categoria","Regra","Fonte","Evidência","Como corrigir","Nível","Obrigatório"],rows=report.checks.map(c=>[c.status,c.category,c.rule,c.source,c.evidence,c.correction,c.level,c.mandatory?"sim":"não"]),data=[h,...rows].map(r=>r.map(csv).join(",")).join("\r\n");save("relatorio-validacao-ufc.csv",`\ufeff${data}`,"text/csv;charset=utf-8")});
$("#print-report").addEventListener("click",()=>window.print());
